SELECT
    e.EMP_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    d.DEPARTMENT_NAME,
    (
        SELECT COUNT(*)
        FROM EMPLOYEE e2
        WHERE e2.DEPARTMENT = e.DEPARTMENT
          AND e2.DOB > e.DOB
    ) AS YOUNGER_EMPLOYEES_COUNT
FROM EMPLOYEE e
JOIN DEPARTMENT d
  ON d.DEPARTMENT_ID = e.DEPARTMENT
ORDER BY e.EMP_ID DESC;
